---
title: "Create country-based rasters"
author: "Rich Cottrell"
date: "20/04/2022"
output: html_document
---
Libraries
```{r}
library(tidyverse)
library(sf)
library(here)
library(terra)
library(rnaturalearth)
library(fasterize)
library(parallel)
library(purrr)

equal_area_gp_proj <- "+proj=cea +lon_0=0 +lat_ts=45 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"

base_raster_ea <- rast(here("data/spatial/base_raster_gall_peters.tif"))

```


Write country shapefiles to raster for terrestrial systems

```{r}

# country shapefiles
countries_shp <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")

#crop feed countries
crop_countries <- readRDS(here("data/tidy_data/demand/total_crop_demand.rds")) |> pull(source_iso3c) |> unique()

crop_countries_shp <- countries_shp |> filter(iso_a3 %in% crop_countries)

#check the crop from the demand data and teh shapefile are now all the same
length(crop_countries_shp |> pull(iso_a3) |> unique())
length(crop_countries)
  
#run it on multiple cores - if it returns null it's because the file already exists

mclapply(X = crop_countries, FUN =  \(this_country){
  
  this_country_filepath <- here(sprintf("data/spatial/00-country-rasters/%s.tif", this_country))
  
  if(!file.exists(this_country_filepath)){
    
    this_country_map <- crop_countries_shp |> filter(iso_a3 == this_country) |> mutate(iso_n3 = as.double(iso_n3))
    
    this_country_raster <- rasterize(x = vect(this_country_map), y = base_raster_ea)
    
    writeRaster(x = this_country_raster, filename = here(sprintf("data/spatial/00-country-rasters/%s.tif", this_country)), overwrite=TRUE)
    
  }
}, mc.cores = detectCores()-2)


```

