---
title: "Spatial Allocation of Forage fish demand from each diet and source"
output: html_document
---
  
```{r}

library(tidyverse)
library(here)
library(terra)
library(sf)
library(data.table)
library(dtplyr)

source(here("src/directories.R"))
source(here("src/spatial.R"))

```


To get the embodied_fish_by_cell.csv file imported below, you need to run the corresponding code in the fisheries section of 02_calculate_global_feed_demand.Rmd. Summarise the embodied fish demand data by cell and gear type that GHG and Disturbance can be assigned to.

```{r}
#this is the embodied demand from each 'area' per diet

forage_demand_totals <- readRDS(here("data/tidy_data/demand/embodied_fish_demand_by_source_diet.rds"))

#this is the embodied demand by cell by gear, species etc 
forage_demand_bycell_list <- fread(here("data/tidy_data/demand/embodied_fish_per_cell.csv")) |> 
  lazy_dt(immutable = FALSE) |> 
  group_by(diet, source_code, LonCentre, LatCentre, FleetGearName) |> 
  summarise(catch_by_gear = sum(adj_embodied_fish, na.rm = TRUE)) |> 
  ungroup() |> 
  as_tibble() |> 
  group_split(diet, source_code)


```

