---
title: "Exploring biodiversity files"
output: html_document
---

This script explores the raw biodiversity shapefiles from IUCN and birds of the world stored on the rdsi storage.

Libraries
```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(sf)
library(dtplyr)
library(terra)

source(here("src/directories.R"))


current_severe_threats_of_interest <- read_csv(here("data/tidy_data/iucn/current_severe_threats_of_interest.csv"))

```

Import threat data
```{r}

current_severe_threats_of_interest <- 
  

```



Convert birds of the world from gdb to shapefile
```{r}

birds_layers <- st_layers(file.path(iucn_dir, "spp_shapefiles/BOTW/BOTW.gdb"))

st_read(file.path(iucn_dir, "spp_shapefiles/BOTW/BOTW.gdb"), layer = "All_Species", METHOD = )

```




All shapefiles 
```{r}
spp_groups <- list.files(file.path(iucn_dir, "spp_shapefiles"))[-grep(pattern = "BOTW", list.files(file.path(iucn_dir, "spp_shapefiles")))] #excluding birds of the wo




birds_filepath <- st_read(file.path(iucn_dir, list.files(sprintf("spp_shapefiles/$s", this_spp_group, pattern )

unique(birds_filepath$binomial)



```

