---
title: "Calculating area loss from species habitats"
output: html_document
---

Libraries
```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(sf)
library(data.table)
library(dtplyr)
library(terra)
library(raster)
library(parallel)
library(rnaturalearth)

source(here("src/directories.R"))

source(here("src/spatial.R"))

base_raster_ea <- rast(here("data/spatial/base_raster_gall_peters.tif"))

select <- dplyr::select

```


Import threat data
```{r}

current_severe_threats_of_interest <- read_csv(here("data/tidy_data/iucn/current_severe_threats_of_interest.csv")) |> 
  rename(id_no = id)
  
#how many species fall in to te category of being affected by these threats? 12728 species
length(unique(current_severe_threats_of_interest$id_no))

#ongoing threats represent 93.9% of all threats
current_severe_threats_of_interest |> filter(result_timing == "Ongoing") |> nrow()/(current_severe_threats_of_interest |> nrow())



```

Import area of soy production using the balanced diet 1 as an example.
```{r}

base_raster_layer <- base_raster_ea |> raster()
base_df <- rasterToPoints(base_raster_layer) |> lazy_dt() |> select(x, y)

#seclect the mammals currently threatened by AG, Aquaculture or fisheries
terrestrial_mammals <- list.files(file.path(iucn_dir, "spp_rasters/MAMMALS_TERRESTRIAL_ONLY"), full.names = TRUE)
ag_threat_index <- which(as.double(gsub("spp_", "", basename(tools::file_path_sans_ext(terrestrial_mammals)))) %in% current_severe_threats_of_interest$id_no, TRUE)
vuln_terrestrial_mammals <- terrestrial_mammals[ag_threat_index]

#select amphibians currently threatened by AG, aquaculture or fisheries
amphibians <- list.files(file.path(iucn_dir, "spp_rasters/ANURA"), full.names = TRUE)
ag_threat_index <- which(as.double(gsub("spp_", "", basename(tools::file_path_sans_ext(amphibians)))) %in% current_severe_threats_of_interest$id_no, TRUE)
vuln_amphibians <- amphibians[ag_threat_index]


#soy protein concentrate raster spatial layers - select top 3 to start with
spc_files <- list.files(here("data/spatial/balanced_diet_1"), pattern = "soy protein concentrate_AllTech_", full.names = TRUE)
spc_files_top_3 <- spc_files[grepl("USA|BRA|CHN", spc_files)]


mammals_aoh <- map(spc_files_top_3, \(this_country){
  
  this_countryname <- gsub(pattern = "soy protein concentrate_AllTech_", replacement = "", basename(tools::file_path_sans_ext(this_country)))
  
  message("processing mammals impacts in ", this_countryname)
  
  
  this_country_spc_raster <- terra::rast(this_country) |> raster()
  
  this_country_spc_dt<- rasterToPoints(this_country_spc_raster) |> lazy_dt() |> rename(crop_area = 3) |> mutate(cell_area = 100)
  
  overlap_list <- mclapply(X = vuln_terrestrial_mammals, FUN = \(this_mammal){
    
    #isolate species
    #this spp id
    this_species <- as.numeric(gsub("spp_", "", basename(tools::file_path_sans_ext(this_mammal))))
    
    #import raster
    this_spp_raster <- rast(this_mammal) |> raster()
    #convert raster layer to species id
    values(this_spp_raster)[!is.na(values(this_spp_raster))] <- this_species
    #get the xyz file
    this_spp_dt <- rasterToPoints(this_spp_raster) |> lazy_dt() |> rename(spp_id = layer)
    
    #inner join species and crop files so we know if they overlap and summarise the crop portion of spp habitat
    spp_crop_overlap <-  this_spp_dt |> 
      inner_join(this_country_spc_dt, by = c("x", "y")) |> 
      group_by(spp_id) |> 
      summarise(aoh = sum(crop_area)/sum(cell_area)) |> 
      as.data.table()
    
  },
  mc.cores = detectCores()-2)
  
  return(rbindlist(overlap_list) |> mutate(country = this_countryname) |> as_tibble)
  
})


write_csv(x = map_df(mammals_aoh, as_tibble), file = here("explore/spc_mammals_aoh_balanced_diet_1.csv"))


#AMPHIBIANS
amphibs_aoh <- map(spc_files_top_3, \(this_country){
  
  this_countryname <- gsub(pattern = "soy protein concentrate_AllTech_", replacement = "", basename(tools::file_path_sans_ext(this_country)))
  
  message("processing amphibians impacts in ", this_countryname)
  
  
  this_country_spc_raster <- terra::rast(this_country) |> raster()
  
  this_country_spc_dt<- rasterToPoints(this_country_spc_raster) |> lazy_dt() |> rename(crop_area = 3) |> mutate(cell_area = 100)
  
  overlap_list <- mclapply(X = vuln_amphibians, FUN = \(this_amphibian){
    
    #isolate species
    #this spp id
    this_species <- as.numeric(gsub("spp_", "", basename(tools::file_path_sans_ext(this_amphibian))))
    
    #import raster
    this_spp_raster <- rast(this_amphibian) |> raster()
    #convert raster layer to species id
    values(this_spp_raster)[!is.na(values(this_spp_raster))] <- this_species
    #get the xyz file
    this_spp_dt <- rasterToPoints(this_spp_raster) |> lazy_dt() |> rename(spp_id = layer)
    
    #inner join species and crop files so we know if they overlap and summarise the crop portion of spp habitat
    spp_crop_overlap <-  this_spp_dt |> 
      inner_join(this_country_spc_dt, by = c("x", "y")) |> 
      group_by(spp_id) |> 
      summarise(aoh = sum(crop_area)/sum(cell_area)) |> 
      as.data.table()
    
  },
  mc.cores = detectCores()-2)
  
   return(rbindlist(overlap_list) |> mutate(country = this_countryname))
  
})


write_csv(x = map_df(amphibs_aoh, as_tibble), file = here("explore/spc_amphibs_aoh_balanced_diet_1.csv"))


```

Illustrate the example of the method through the mammals in Brazil, China, USA

```{r}

amphib_impacts <- read_csv(file = here("explore/spc_amphibs_aoh_balanced_diet_1.csv"))
mammals_impacts <- read_csv(file = here("explore/spc_mammals_aoh_balanced_diet_1.csv"))

spc_rasters <- list.files(here("data/spatial/balanced_diet_1"), pattern = "soy protein concentrate_AllTech_", full.names = TRUE)
brazil_spc_raster <- rast(spc_rasters[grepl("BRA", spc_rasters)]) |> raster()

spc_df <- brazil_spc_raster |> as("SpatialPointsDataFrame") |> as.data.frame() |> filter(spam2010V2r0_global_A_SOYB_A>0)

#using species 6228 as an example as the proportion is large

mammals_shp <- st_read(dsn = file.path("/mnt/rdsi/raw_data/iucn/spp_shapefiles/MAMMALS_TERRESTRIAL_ONLY/MAMMALS_TERRESTRIAL_ONLY.shp"), layer = "MAMMALS_TERRESTRIAL_ONLY" ) 

shp_29404 <- mammals_shp |> filter(id_no == 29404)|> st_transform(crs = equal_area_gp_proj)
shp_6288 <- mammals_shp |> filter(id_no == 6288) |> st_transform(crs = equal_area_gp_proj)
shp_29404 <- mammals_shp |> filter(id_no == 29404) |> st_transform(crs = equal_area_gp_proj)
shp_14224 <- mammals_shp |> filter(id_no == 14224) |> st_transform(crs = equal_area_gp_proj)


countries_shp <- ne_countries(scale = 110, returnclass = "sf") |> st_transform(equal_area_gp_proj) 

brazil_shp <- countries_shp |> filter(geounit %in% c("Brazil", "Peru", "Ecuador", "Chile", "Colombia", "Argentina", "Paraguay", "Uruguay", "Bolivia", "Venezuela", "Guyana", "French Guiana", "Panama", "Costa Rica", "Suriname"))

(p <- ggplot()+
  geom_sf(data = brazil_shp, fill="grey", colour="white")+
  geom_sf(data = shp_14224, fill = "darkgreen", colour=NA, alpha=0.7)+
  geom_sf(data = shp_6288, fill = "blue", colour=NA, alpha=0.5)+
  geom_tile(data = spc_df, aes(x = x, y = y, fill = spam2010V2r0_global_A_SOYB_A))+
  scale_fill_gradientn(colors = RColorBrewer::brewer.pal(n=9, name = "BuPu"))+
  theme_bw()+
    theme(title = element_text(size=7))+
    labs(fill = "Soy production\n(km2)", title = "Myrmecophaga tridactyla (Giant anteater) - green\nDasypus hybridus (Southern long-nosed armadillo) - blue"))

ggsave(filename = here("explore/explore_brazil_species_impacts.jpg"), device = "jpg", dpi=300, height = 20, width = 15, units =  "cm")

```

Compare countries for mammal impacts

```{r}
my_pal <- rcartocolor::carto_pal(n = , name = "Bold")[c(1, 7, 2)]

mammals_impacts2 <- mammals_impacts |> group_by(country) |>add_tally()

ggplot(mammals_impacts2, 
       aes(x = country, y = aoh*100, fill = country))+
    ggdist::stat_gradientinterval(
    width = .3, 
    color = "black", 
    fill_type = "gradient")+
  geom_jitter(alpha = 0.5, width = 0.1, colour = "grey50")+
  theme_bw()+
  scale_fill_manual(values = my_pal, guide = "none")+
  #scale_color_manual(values = my_pal, guide = "none")+
  geom_text(data = mammals_impacts2 |> select(c(3,4)) |> distinct() |> mutate(y = 12),
            aes(x = country, y = y, label = n), colour = "black")+
  labs(y = "Area of habitat (%)", x= "", title = "SPC - Area of mammal habitat")

ggsave(filename = here("explore/comparison of mammal impacts for countries - spc .jpg"), device = "jpg", dpi = 300, width = 15, height = 12, units = "cm")

```

