---
title: "09_forage_fish_nutrient_pressures"
author: "Rich Cottrell"
date: "15/07/2022"
output: html_document
---


```{r setup}

library(tidyverse)
library(terra)
library(here)

source(here("src/directories.R"))

select <- dplyr::select


```

For each diet and source import the rasters from ghg and make all values zero - then rexport into "int" folder with nutrient file names - for both nitrogen and phosphorus

# Nitrogen pollution

Fishmeal

```{r}

fm_template_files <- list.files(path = here("data/spatial/marine_diet/int"), pattern = "fishmeal_ghg", full.names = TRUE)
fm_template_files <- fm_template_files[grepl("allocation", fm_template_files)]

this_file <- fm_template_files[[3]]

map(.x = fm_template_files, .f = \(this_file){
  
  filename <- tools::file_path_sans_ext(this_file)
  
  this_source <- str_extract(this_file, "EPC|NAT|OTH")
  
  this_allocation_method <- str_extract(this_file, "ge_allocation|mass_allocation")
  
  saveName_N_md <- sprintf(here("data/spatial/marine_diet/int/fishmeal_N_km2_%s_%s.tif"), this_source, this_allocation_method)
  saveName_N_pd <- sprintf(here("data/spatial/plant_diet/int/fishmeal_N_km2_%s_%s.tif"), this_source, this_allocation_method)
  
  if(!file.exists(saveName_N_md) | !file.exists(saveName_N_pd)){
    
    this_r <- rast(this_file)*0
    names(this_r) <- "total_N_km2"
    
    #save N rasters
    terra::writeRaster(x = this_r, filename = saveName_N_md, overwrite = TRUE)
    
    terra::writeRaster(x = this_r, filename = saveName_N_pd, overwrite = TRUE)
    
  }
  
})

```

Fish oil

```{r}

fo_template_files <- list.files(path = here("data/spatial/marine_diet/int"), pattern = "fish oil_ghg", full.names = TRUE)
fo_template_files <- fo_template_files[grepl("allocation", fo_template_files)]


this_file <- fo_template_files[[3]]


map(.x = fo_template_files, .f = \(this_file){
  
  filename <- tools::file_path_sans_ext(this_file)
  
  this_source <- str_extract(this_file, "EPC|NAT|OTH")
  
  this_allocation_method <- str_extract(this_file, "ge_allocation|mass_allocation")
  
  saveName_N_md <- sprintf(here("data/spatial/marine_diet/int/fish oil_N_km2_%s_%s.tif"), this_source, this_allocation_method)
  saveName_N_pd <- sprintf(here("data/spatial/plant_diet/int/fish oil_N_km2_%s_%s.tif"), this_source, this_allocation_method)
  
  if(!file.exists(saveName_N_md) | !file.exists(saveName_N_pd)){
    
    this_r <- rast(this_file)*0
    names(this_r) <- "total_N_km2"
    
    #save N rasters
    terra::writeRaster(x = this_r, filename = saveName_N_md, overwrite = TRUE)
    
    terra::writeRaster(x = this_r, filename = saveName_N_pd, overwrite = TRUE)
    
  }
  
})

```



# Phosphorus pollution

Fishmeal

```{r}
fm_template_files <- list.files(path = here("data/spatial/marine_diet/int"), pattern = "fishmeal_ghg", full.names = TRUE)
fm_template_files <- fm_template_files[grepl("allocation", fm_template_files)]

this_file <- fm_template_files[[3]]


map(.x = fm_template_files, .f = \(this_file){
  
  filename <- tools::file_path_sans_ext(this_file)
  
  this_source <- str_extract(this_file, "EPC|NAT|OTH")
  
  this_allocation_method <- str_extract(this_file, "ge_allocation|mass_allocation")
  
  saveName_P_md <- sprintf(here("data/spatial/marine_diet/int/fishmeal_P_km2_%s_%s.tif"), this_source, this_allocation_method)
  saveName_P_pd <- sprintf(here("data/spatial/plant_diet/int/fishmeal_P_km2_%s_%s.tif"), this_source, this_allocation_method)
  
  if(!file.exists(saveName_P_md) | !file.exists(saveName_P_pd)){
  
  this_r <- rast(this_file)*0
  names(this_r) <- "total_P_km2"
  
  #save P rasters
  terra::writeRaster(x = this_r, filename = saveName_P_md, overwrite = TRUE)
  
  terra::writeRaster(x = this_r, filename = saveName_P_pd, overwrite = TRUE)
  }
  
  })


```


Fish oil 

```{r}
fo_template_files <- list.files(path = here("data/spatial/marine_diet/int"), pattern = "fish oil_ghg", full.names = TRUE)
fo_template_files <- fo_template_files[grepl("allocation", fo_template_files)]


this_file <- fo_template_files[[3]]


map(.x = fo_template_files, .f = \(this_file){
  
  filename <- tools::file_path_sans_ext(this_file)
  
  this_source <- str_extract(this_file, "EPC|NAT|OTH")
  
  this_allocation_method <- str_extract(this_file, "ge_allocation|mass_allocation")
  
  saveName_P_md <- sprintf(here("data/spatial/marine_diet/int/fish oil_P_km2_%s_%s.tif"), this_source, this_allocation_method)
  saveName_P_pd <- sprintf(here("data/spatial/plant_diet/int/fish oil_P_km2_%s_%s.tif"), this_source, this_allocation_method)
  
  if(!file.exists(saveName_P_md) | !file.exists(saveName_P_pd)){
  
  this_r <- rast(this_file)*0
  names(this_r) <- "total_P_km2"
  
  #save P rasters
  terra::writeRaster(x = this_r, filename = saveName_P_md, overwrite = TRUE)
  
  terra::writeRaster(x = this_r, filename = saveName_P_pd, overwrite = TRUE)
  }
  
  })



rm(list = ls())
```



