---
title: "10_forage_fish_water_extraction_pressures"
author: "Rich Cottrell"
date: "15/07/2022"
output: html_document
---


```{r setup}

library(tidyverse)
library(terra)
library(here)

source(here("src/directories.R"))

select <- dplyr::select


#allocation method (un-comment preference)
source(here("1_choose_allocation_method.R")) #selects from set up script
#this_allocation_method <- "econ_allocation"
# this_allocation_method <- "ge_allocation"
#this_allocation_method <- "mass_allocation"



```

For each diet and source import the rasters from ghg and make all values zero - then rexport into "pressures" folder. Do this Fishmeal and Fish oil


Fishmeal

```{r}

fm_template_files <- list.files(path = here("data/spatial/marine_diet/int"), pattern = "fishmeal_ghg_km2", full.names = TRUE)
fm_template_files <- fm_template_files[grepl(this_allocation_method, fm_template_files)]

this_file <- fm_template_files[[1]]


map(.x = fm_template_files, .f = \(this_file){
  
  filename <- tools::file_path_sans_ext(this_file)
  
  this_source <- str_sub(filename, start = nchar(filename)-1, end = nchar(filename))
  
  saveName_md <- sprintf(here("data/spatial/marine_diet/int/fishmeal_water_km2_%s_%s.tif"), this_allocation_method, this_source)
  saveName_pd <- sprintf(here("data/spatial/plant_diet/int/fishmeal_water_km2_%s_%s.tif"), this_allocation_method, this_source)
  
  if(!file.exists(saveName_md) | !file.exists(saveName_pd)){
  
  this_r <- rast(this_file)*0
  names(this_r) <- "total_h20_km2"
  
  terra::writeRaster(x = this_r, filename = saveName_md, overwrite = TRUE)
  
  terra::writeRaster(x = this_r, filename = saveName_pd, overwrite = TRUE)
  }
  
  })

```

Fish oil


```{r}
fo_template_files <- list.files(path = here("data/spatial/marine_diet/int"), pattern = "fish oil_ghg_km2", full.names = TRUE)
fo_template_files <- fo_template_files[grepl(this_allocation_method, fo_template_files)]

this_file <- fo_template_files[[1]]


map(.x = fo_template_files, .f = \(this_file){
  
  filename <- tools::file_path_sans_ext(this_file)
  
  this_source <- str_sub(filename, start = nchar(filename)-1, end = nchar(filename))
  
  saveName_md <- sprintf(here("data/spatial/marine_diet/int/fish oil_water_km2_%s_%s.tif"),  this_allocation_method, this_source)
  saveName_pd <- sprintf(here("data/spatial/plant_diet/int/fish oil_water_km2_%s_%s.tif"), this_allocation_method, this_source)
  
  if(!file.exists(saveName_md) | !file.exists(saveName_pd)){
  
  this_r <- rast(this_file)*0
  names(this_r) <- "total_h20_km2"
  
  terra::writeRaster(x = this_r, filename = saveName_md, overwrite = TRUE)
  
  terra::writeRaster(x = this_r, filename = saveName_pd, overwrite = TRUE)
  }
  
  })
```


```{r}
#clear the environment
rm(list = ls(all.names = TRUE))
```



