---
title: "12_crop_disturbances_pressures_B"
author: "Rich Cottrell"
date: '2023-11-07'
output: html_document
---


This script combines the demand rasters for crop raw materials for each diet across sources

```{r setup}

library(tidyverse)
library(terra)
library(here)

source(here("src/directories.R"))
source(here("src/functions.R"))

select <- dplyr::select

#allocation method (un-comment preference)
#this_allocation_method <- "econ_allocation"
#this_allocation_method <- "ge_allocation"
#this_allocation_method <- "mass_allocation"


```


Marine diets

```{r}

md_crop_r_list <- list.files(here("data/spatial/marine_diet/production"), pattern = paste0("AllTech_", this_allocation_method), full.names = TRUE)


this_file <- md_crop_r_list[[7]]


#multiply production demand rasters by the land-use value for production from each country

map(md_crop_r_list, \(this_file){
  
  this_ingredient <- stringr::str_extract(basename(this_file), "[^_]+")
  
  this_raw_material <- 
    readRDS(here("data/tidy_data/demand/total_crop_demand.rds")) |> 
    select(ingredients, FAOSTAT_name) |> 
    distinct() |> 
    filter(ingredients == this_ingredient) |> 
    pull(FAOSTAT_name)
  
  this_filename <- tools::file_path_sans_ext(basename(this_file))
  
  this_diet <- "marine_diet"
  
  this_source <- substr(x = this_filename, start = nchar(this_filename)-2, stop = nchar(this_filename))
  
  saveName <- sprintf(here("data/spatial/%s/int/%s_disturbance_km2_%s_%s.tif"), this_diet, this_ingredient,this_allocation_method, this_source)
  
  if(!file.exists(saveName)){
    
    message("Processing... ", basename(this_file))
    
    this_disturbance_value_kg <- readRDS(here("data/tidy_data/LCA/crop_lca.rds")) |> 
      filter(FAOSTAT_name == this_raw_material &iso3c == this_source & impact== "Land use" & allocation == this_allocation_method) |> 
      pull(value_tonne)
    
    this_disturbance_value_tonne <- this_disturbance_value_kg/1e6 #from m2 to km2 
    
    this_rast <- rast(this_file)
    
    this_rast_km2 <- this_rast/cellSize(this_rast, unit = "km")
    
    this_disturbance_rast <- this_rast_km2*this_disturbance_value_tonne
    names(this_disturbance_rast) <- "km2"
    
    writeRaster(x = this_disturbance_rast, filename = saveName, overwrite=TRUE)
    
  }
})



```


PLANT DIETS
```{r}
pd_crop_r_list <- list.files(here("data/spatial/plant_diet/production"), pattern = paste0("AllTech_", this_allocation_method), full.names = TRUE)

this_file <- pd_crop_r_list[[1]]


#multiply production demand rasters by the ghg value for production from each country

map(pd_crop_r_list, \(this_file){
  
  this_ingredient <- stringr::str_extract(basename(this_file), "[^_]+")
  
  this_raw_material <- readRDS(here("data/tidy_data/demand/total_crop_demand.rds")) |> select(ingredients, FAOSTAT_name) |> distinct() |> filter(ingredients == this_ingredient) |> pull(FAOSTAT_name)

  this_filename <- tools::file_path_sans_ext(basename(this_file))
  
  this_diet <- "plant_diet"
  
  this_source <- substr(x = this_filename, start = nchar(this_filename)-2, stop = nchar(this_filename))
  
  saveName <- sprintf(here("data/spatial/%s/int/%s_disturbance_km2_%s_%s.tif"), this_diet, this_ingredient,this_allocation_method, this_source)
  
  if(!file.exists(saveName)){
    
    message("processing... ", basename(this_file))
    
    this_disturbance_value_kg <- readRDS(here("data/tidy_data/LCA/crop_lca.rds")) |> 
      filter(FAOSTAT_name == this_raw_material &iso3c == this_source & impact== "Land use" & allocation == this_allocation_method) |> 
      pull(value_tonne)
    
    this_disturbance_value_tonne <- this_disturbance_value_kg/1e6 #from m2 to km2 
    
    this_rast <- rast(this_file)
    
    this_rast_km2 <- this_rast/cellSize(this_rast, unit = "km")
    
    this_disturbance_rast <- this_rast_km2*this_disturbance_value_tonne
    names(this_disturbance_rast) <- "km2"
    
    writeRaster(x = this_disturbance_rast, filename = saveName, overwrite=TRUE)
    
  }
})
```


```{r}
#clear the environment
rm(list = ls(all.names = TRUE))
```

