---
title: "Rescaling environmental pressures"
author: "Rich Cottrell"
date: "30/06/2022"
output: html_document
---

This file is used to rescale all rasters' values for each pressure so that values among feeds may be compared.

```{r}

library(tidyverse)
library(terra)
library(here)

select <- dplyr::select
values <- terra::values

source(here("src/fxns.R"))
```


## Disturbance

Bring in  forage fish and crop layers for disturbance for both diets. Look at the values to establish a percentile to use for rescaling.

```{r}

#ID files for disturbance for marine and plant diets
marine_diet_disturbance <- list.files(here("data/spatial/marine_diet/int"), pattern = "disturbance_km2", full.names = TRUE)
plant_diet_disturbance <- list.files(here("data/spatial/plant_diet/int"), pattern = "disturbance_km2", full.names = TRUE)

#which diet has the highest disturbance values
marine_disturbance_vals <- marine_diet_disturbance |> map(rast) |> map(no_na_values) |> unlist()
plant_disturbance_vals <- plant_diet_disturbance |> map(rast) |> map(no_na_values) |> unlist()

#check marine is appearing more intense (given forage fish distrubance values are much higher)
summary(marine_disturbance_vals)
summary(plant_disturbance_vals)

all_disturbance_vals <- c(marine_disturbance_vals, plant_disturbance_vals)


#determine the quantile for rescaling
hist(unlist(all_disturbance_vals), main = "", xlab = "Disturbance values") |> 
abline(v = quantile(all_disturbance_vals, 1), lty=2)


disturbance_rescale_val <- quantile(all_disturbance_vals, 1) |> as.numeric()


#rescale all rasters by the 99.9th percentile

#marine diets

this_file <- marine_diet_disturbance[[1]]


rescaled_marine_disturbance_rasters <- 
  
  map(.x= marine_diet_disturbance, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/marine_diet/pressures/%s"), this_basename)
  
  if(file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = if_else(x>disturbance_rescale_val, true = 1, false = x/disturbance_rescale_val))
    })
    
    names(this_rescaled_rast) <- tools::file_path_sans_ext(this_basename)
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
    
    return(this_rescaled_rast)
  }
})


#plant diets

rescaled_plant_disturbance_rasters <- 
  
  map(.x= plant_diet_disturbance, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/plant_diet/pressures/%s"), this_basename)
  
  if(file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = if_else(x>disturbance_rescale_val, true = 1, false = x/disturbance_rescale_val))
    })
    
    names(this_rescaled_rast) <- tools::file_path_sans_ext(this_basename)
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
    
    return(this_rescaled_rast)
  }
  
})


# compare rescaled rasters

plot(rast(rescaled_marine_disturbance_rasters))
plot(rast(rescaled_plant_disturbance_rasters))

```
# Greenhouse gas pressures

Need to remove the email raster layers

```{r}

marine_diet_ghg <- list.files(here("data/spatial/marine_diet/int"), pattern = "ghg", full.names = TRUE)
plant_diet_ghg <- list.files(here("data/spatial/plant_diet/int"), pattern = "ghg", full.names = TRUE)

#get the raster values from files
marine_ghg_vals <- marine_diet_ghg |> map(rast) |> map(no_na_values) |> unlist()
plant_ghg_vals <- plant_diet_ghg |> map(rast) |> map(no_na_values) |> unlist()

#check plant is appearing more intense (given crop ghg values are much higher)
summary(marine_ghg_vals)
summary(plant_ghg_vals)

all_ghg_vals <- c(marine_ghg_vals, plant_ghg_vals)

#explore a reasonable rescale value
hist(all_ghg_vals, main = "", xlab = "GHG values") |> 
abline(v=quantile(all_ghg_vals, 1), lty = 2)

#select the 99.99th percentile for rescaling
ghg_rescale_val <- quantile(all_ghg_vals, 1) |> as.numeric()

#test file
this_file <- marine_diet_ghg[[1]]

#Rescale all ghg rasters to the 99.99th percentile
rescaled_marine_ghg_rasters <- 
  
  map(.x= marine_diet_ghg, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/marine_diet/pressures/%s"), this_basename)
  
  if(file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = if_else(x>ghg_rescale_val, true = 1, false = x/ghg_rescale_val))
                  })
    names(this_rescaled_rast) <- tools::file_path_sans_ext(this_basename)
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
    
    return(this_rescaled_rast)
  }
  
})



#PLANT DIETS

#test file

this_file <- plant_diet_ghg[[1]]

rescaled_plant_ghg_rasters <- 
  
  map(.x= plant_diet_ghg, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/plant_diet/pressures/%s"), this_basename)
  
  if(file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = if_else(x>ghg_rescale_val, true = 1, false = x/ghg_rescale_val))
    })
    
    names(this_rescaled_rast) <- tools::file_path_sans_ext(this_basename)
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
    
    return(this_rescaled_rast)
    
  }
  
})


#check layers
plot(rast(rescaled_marine_ghg_rasters))
plot(rast(rescaled_plant_ghg_rasters))


```

# Nutrient pressures
```{r}

marine_diet_N <- list.files(here("data/spatial/marine_diet/int"), pattern = "_N_", full.names = TRUE)

plant_diet_N <- list.files(here("data/spatial/plant_diet/int"), pattern = "_N_", full.names = TRUE)

all_N <- c(marine_diet_N, marine_diet_N)

this_file <- all_N[[1]]

all_N_vals <- unlist(map(.x = all_N, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  these_rast_values <- as.vector(values(this_rast, na.rm=TRUE))
  
  return(these_rast_values)
}))


# rescale by the 99.9th percentile
hist(all_N_vals, main = "", xlab = "Nitrogen values")
abline(v=quantile(all_N_vals, 0.999), lty = 2)


N_rescale_val <- quantile(all_N_vals, 0.999)


# Now rescale pressure by the rescale value 

#marine diets - Nitrogen

this_file <- marine_diet_N[[1]]

map(.x= marine_diet_N, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/marine_diet/pressures/%s"), this_basename)
  
  if(!file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = 
                  if_else(x>N_rescale_val, true = 1, false = x/N_rescale_val))})
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
  }
  
})



#plant diets _ Nitrogen

map(.x= plant_diet_N, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/plant_diet/pressures/%s"), this_basename)
  
  if(!file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = 
                  if_else(x>N_rescale_val, true = 1, false = x/N_rescale_val))})
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
    
  }
  
})








# Phosphorus

marine_diet_P <- list.files(here("data/spatial/marine_diet/int"), pattern = "_P_", full.names = TRUE)

plant_diet_P <- list.files(here("data/spatial/plant_diet/int"), pattern = "_P_", full.names = TRUE)

all_P <- c(marine_diet_P, marine_diet_P)

this_file <- all_P[[1]]

all_P_vals <- unlist(map(.x = all_P, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  these_rast_values <- as.vector(values(this_rast, na.rm=TRUE))
  
  return(these_rast_values)
}))




hist(all_P_vals, main = "", xlab = "Phosphorus values")
abline(v=quantile(all_P_vals, 0.999), lty = 2)

P_rescale_val <- quantile(all_P_vals, 0.999) |> as.numeric()




# Now rescale pressure by the rescale value 

#marine diets - Phosphorus

this_file <- marine_diet_P[[1]]

map(.x= marine_diet_P, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/marine_diet/pressures/%s"), this_basename)
  
  if(!file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = 
                  if_else(x>P_rescale_val, true = 1, false = x/P_rescale_val))})
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
  }
  
})



#plant diets - Phosphorus

map(.x= plant_diet_P, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/plant_diet/pressures/%s"), this_basename)
  
  if(!file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = 
                  if_else(x>P_rescale_val, true = 1, false = x/P_rescale_val))})
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
    
  }
  
})





```


# Water extraction
```{r}

marine_diet_h2o <- list.files(here("data/spatial/marine_diet/int"), pattern = "_water_", full.names = TRUE)

plant_diet_h2o <- list.files(here("data/spatial/plant_diet/int"), pattern = "_water_", full.names = TRUE)

all_h2o <- c(marine_diet_h2o, marine_diet_h2o)

this_file <- all_h2o[[1]]

all_h2o_vals <- unlist(map(.x = all_h2o, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  these_rast_values <- as.vector(values(this_rast, na.rm=TRUE))
  
  return(these_rast_values)
}))




hist(all_h2o_vals, main = "", xlab = "Water values")
abline(v=quantile(all_h2o_vals, 0.999), lty = 2)


water_rescale_val <- quantile(all_h2o_vals, 0.999)





#marine diets - Water

map(.x= marine_diet_h2o, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/marine_diet/pressures/%s"), this_basename)
  
  if(!file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = 
                  if_else(x>water_rescale_val, true = 1, false = x/water_rescale_val))})
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
  }
  
})



#plant diets - water

map(.x= plant_diet_h2o, .f = \(this_file){
  
  this_rast <- rast(this_file)
  
  this_basename <- str_replace(basename(this_file), pattern = "_km2", replacement = "")
  
  saveName <- sprintf(here("data/spatial/plant_diet/pressures/%s"), this_basename)
  
  if(!file.exists(saveName)){
    
    this_rescaled_rast <- 
      app(x = this_rast, fun = \(x){
        if_else(x<0, true = 0, false = 
                  if_else(x>water_rescale_val, true = 1, false = x/water_rescale_val))})
    
    writeRaster(x = this_rescaled_rast, filename = saveName, overwrite=TRUE)
    
  }
  
})


```







