---
title: "16 Conceptual plot of diets and approach"
author: "Rich Cottrell"
date: "14/02/2023"
output: html_document
---

Set up
```{r}
library(tidyverse)
library(ggpubr)
library(patchwork)
library(here)
library(sf)
library(terra)
library(rnaturalearth)
#library(rnaturalearthdata)
library(RColorBrewer)
library(gameofthrones)
library(parallel)
library(ggdist)
library(data.table)
library(dtplyr)


# taking cumulative impoact palette from Halpern et al 
red <- "#B90000"
d_brown <- "#515256"
m_brown <- "#B27B54"
l_brown <- "#BC995F"
green <- "#A8B072"
yellow<- "#EFCE71"
l_yellow <- "#F7F6C1"
light_gray <- "#F8F9FA"
discrete_pal <- c(l_yellow, yellow, green, l_brown, m_brown, d_brown, "firebrick")
continuous_pal <-  colorRampPalette(discrete_pal, space="Lab", bias = 3.5)(10000)
final_palette <- c(light_gray, continuous_pal, red)

#source files
source(here("src/fxns.R"))

#spatial products
moll_crs <- "ESRI:53009"
gp_crs <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"


countries <-    ne_countries(scale = "medium", returnclass = "sf") |> st_transform(crs = moll_crs)
bbox <- ne_download(scale = 50, type = "wgs84_bounding_box", category = "physical", returnclass = "sf") |> st_transform(crs = moll_crs)
coastline <- ne_coastline(scale = 50, returnclass = "sf") |> st_transform(crs = moll_crs)
select <- dplyr::select
values <- terra::values
```


Explanatory plot of the two diets

```{r}
marine_diet <- readRDS(here("data/tidy_data/diet-scenarios/marine_diet.rds")) |> 
  filter(prop >0) |> 
  add_row(groups = "Microingredients", ingredients = "microingredients", diet = "marine_diet", prop = 0.02) |> 
  mutate(ingredients = case_when(ingredients == "canola/camelina oil" ~ "Canola oil",
                                  TRUE ~ str_to_sentence(ingredients)),
         ingredients = gsub(pattern = "-wild", replacement = "", ingredients)) |> 
  mutate(ingredients = factor(ingredients, levels = c("Fishmeal", "Fish oil", "Faba beans", "Soybean meal", "Corn gluten meal", "Wheat gluten", "Wheat", "Microingredients"))) |> 
  mutate(cum_prop = cumsum(prop)) |> 
  mutate(label_y_pos = if_else(condition = prop != prop[1], true = prop/2+lag(cum_prop), false = cum_prop/2)) |> 
  mutate(label_y_pos = 1-label_y_pos) 


plant_diet <- readRDS(here("data/tidy_data/diet-scenarios/plant_diet.rds")) |> 
  filter(prop >0) |> 
  add_row(groups = "Microingredients", ingredients = "microingredients", diet = "plant_diet", prop = 0.04) |> 
  mutate(ingredients = case_when(ingredients == "canola/camelina oil" ~ "Canola oil",
                                  TRUE ~ str_to_sentence(ingredients)),
         ingredients = gsub(pattern = "-wild", replacement = "", ingredients)) |> 
  mutate(ingredients = factor(ingredients, levels = c("Fishmeal", "Fish oil", "Soy protein concentrate", "Corn gluten meal","Faba beans", "Pea protein concentrate",  "Sunflower meal", "Wheat gluten", "Canola oil", "Linseed oil", "Wheat", "Pea starch", "Corn starch", "Microingredients"))) |> 
  mutate(cum_prop = cumsum(prop)) |> 
  mutate(label_y_pos = if_else(condition = prop != prop[1], true = prop/2+lag(cum_prop), false = cum_prop/2))|> 
   mutate(label_y_pos = 1-label_y_pos) 

#check totals 
marine_diet |> pull(prop) |> sum() #adds to 1
plant_diet |> pull(prop) |> sum() #adds to 1

ingredient_levels <- c( "Fishmeal",  "Fish oil" , "Soybean meal","Corn gluten meal" , "Faba beans" , "Wheat gluten" ,"Wheat" , "Soy protein concentrate",   "Pea protein concentrate","Sunflower meal","Canola oil","Linseed oil","Pea starch","Corn starch", "Microingredients")

#get a plot and legend for each diet
marine_diet_plot <- ggplot(data = marine_diet,
       aes(x=diet, y = prop, fill = ingredients))+
  geom_col()+
  scale_fill_manual(values =  rev(colorRampPalette(colors = rcartocolor::carto_pal(n = 9, name = "Earth"))(16))[c(1:7,16)])
marine_legend <- get_legend(marine_diet_plot)
plant_diet_plot <- ggplot(data = plant_diet,
       aes(x=diet, y = prop, fill = ingredients))+
  geom_col()+
  scale_fill_manual(values =  rev(colorRampPalette(colors = rcartocolor::carto_pal(n = 9, name = "Earth"))(16))[c(1,2,5:16)])
plant_legend <- get_legend(plant_diet_plot)


#combine both diets
both_diets <- bind_rows(marine_diet, plant_diet) |> 
  
  mutate(label_x_pos = if_else(diet =="marine_diet", true =0.5, false = 2.5)) |> 
  mutate(diet = if_else(condition = diet == "marine_diet", true = "Marine-\ndominant", false = "Plant-\ndominant")) |> 
  mutate(hjust = if_else(condition = diet == "marine_diet", true = 1, false = 0)) |> 
  mutate(ingredients = factor(ingredients, levels = rev(ingredient_levels))) |> 
  mutate(diet = factor(diet, levels = rev(c("Plant-\ndominant", "Marine-\ndominant"))))

both_diets_p <- ggplot(data = both_diets,
       aes(x = diet , y = prop, fill = ingredients))+
  geom_col()+
  scale_fill_manual(values =  (colorRampPalette(colors = rcartocolor::carto_pal(n = 7, name = "Earth"))(16)))+
  theme_pubr()+
  theme(legend.title = element_blank(),
        legend.text = element_text(size=7),
        text = element_text(size=8),
        legend.position = "right",
        #legend.box.spacing = unit(-0.1, "cm"),
        panel.grid = element_blank(),
        legend.key.size = unit(0.25, "cm")
        )+
  labs(x = "Feed scenario", y = "Proportion")+
  guides(fill = guide_legend(byrow=TRUE, reverse = FALSE, ncol = 1))

ggsave(filename = here("figures/feed_composition.jpg"), dpi = 600, width = 10, height = 9, units = "cm")
```

Some statistics on the number of species/crop raw materials/countries/marine regions needed to support demand. 

```{r}
forage_fish <- data.table::fread(here("data/tidy_data/demand/embodied_fish_per_cell.csv"))
forage_fish_md <- forage_fish |> filter(diet == "marine_diet") |> as_tibble()
unique(forage_fish$CommonName)
sum(forage_fish_md$total_catch)


#Number of countries for crops
countries_regions <-
  c(list.files("/mnt/rdsi/github/feed_pressure_mapping/data/spatial/marine_diet/pressures", full.names = TRUE), list.files("/mnt/rdsi/github/feed_pressure_mapping/data/spatial/plant_diet/pressures", full.names = TRUE)) |>
  map(.f = \(this_element){
    sans_ext <- tools::file_path_sans_ext(this_element)
    
    last_3 <-  str_sub(string = sans_ext, start = nchar(sans_ext)-2, end = nchar(sans_ext))
    return(last_3)
  }) |> 
  unlist() |> 
  unique() 


length(countries_regions[!countries_regions %in% c("EPC", "NAT", "OTH")]) # 18 countries used and 3 marine regions


#number of crop types
total_crop_demand <- readRDS("/mnt/rdsi/github/feed_pressure_mapping/data/tidy_data/demand/total_crop_demand.rds") 
total_crop_demand |> pull(FAOSTAT_name) |> unique()
total_crop_demand |> filter(FAOSTAT_name == "Pulses nes")
#forage fish embodied demand by regions
embodied_fish_bysource <- readRDS(here("data/tidy_data/demand/embodied_fish_demand_by_source_diet.rds")) |> 
  mutate(source_code = case_when(source_code == "EPC" ~ "Eastern Pacific",
                                 source_code == "NAT" ~ "North Atlantic",
                                 source_code == "OTH" ~ "All other regions")) |> 
  mutate(source_code = factor(source_code, levels = c("Eastern Pacific", "North Atlantic", "All other regions"))) |> 
  mutate(diet = if_else(diet=="marine_diet", true = "Marine-dominant\nfeed", false = "Plant-dominant\nfeed"))

#how much more embodied fish does a marine diet create relative to plant?
source_codes <- unique(embodied_fish_bysource$source_code) |> as.character()
diff_list_ge <- list()
diff_list_mass <- list()
amount_list <- list()

for(s in source_codes){
 
  marine_plant_ratio_ge <-  
    (embodied_fish_bysource |> filter(source_code == s & allocation == "Energetic allocation" & diet == "Marine-dominant\nfeed" & demand_from == "Total") |> pull(embodied_fish))/(embodied_fish_bysource |> filter(source_code == s & allocation == "Energetic allocation" & diet == "Plant-dominant\nfeed" & demand_from == "Total") |> pull(embodied_fish))
  
  marine_plant_ratio_mass <-  
    (embodied_fish_bysource |> filter(source_code == s & allocation == "Mass allocation" & diet == "Marine-dominant\nfeed" & demand_from == "Total") |> pull(embodied_fish))/(embodied_fish_bysource |> filter(source_code == s & allocation == "Mass allocation" & diet == "Plant-dominant\nfeed" & demand_from == "Total") |> pull(embodied_fish))
  
  
 diff_list_ge[which(source_codes==s)] <- marine_plant_ratio_ge
 
 diff_list_mass[which(source_codes==s)] <- marine_plant_ratio_mass
 
}

unlist(diff_list_ge) #~2.2 across all regions and allocation methods=
unlist(diff_list_mass)

#Differences among regions within marine-dominant feed
embodied_fish_bysource |> 
  filter(diet == "Marine-dominant\nfeed" & demand_from == "Total") |> 
  arrange(-embodied_fish) |> 
  mutate(region_diff = max(embodied_fish)-embodied_fish)
embodied_fish_bysource |>
  filter(demand_from =="Total") |> 
  group_by(diet, allocation) |> 
  summarise(mean = mean(embodied_fish, na.rm=TRUE),
            sd = sd(embodied_fish, na.rm=TRUE))


ggplot(data = embodied_fish_bysource) +
  aes(x = demand_from, y = embodied_fish/1000, fill = source_code)+
  geom_bar(stat= "identity", position = "dodge")+
  facet_grid(rows = vars(diet), cols = vars(allocation), scales = "fixed")+
  
  labs(fill = "Origin", y = "Embodied fish demand (1000s T)")+
  scale_fill_manual(values = c("#edf8b1", "#7fcdbb", "#2c7fb8"))+
  theme_bw()+
  theme(legend.position = c(0.75, 0.43),
        legend.background = element_rect(fill="transparent"), 
        legend.direction = "horizontal",
        axis.title.x = element_blank(),
        panel.grid = element_blank(), 
        text = element_text(size=12),
        legend.text = element_text(size = 10))+
  guides(fill = guide_legend(title.position = "top"))

ggsave(filename = here("figures/presos/embodied_forage_fish_demand.jpg"), device="jpg", dpi = 600, width = 18, height = 15, units="cm")
ggsave(filename = here("figures/supplementary/embodied_forage_fish_demand.jpg"), device="jpg", dpi = 600, width = 18, height = 15, units="cm")



#find reasons for differences in demand
#blue whiting looks like the main reason with European sprat also. Comparing the embodied fish versus the catch both Sprat and Whiting rank as higher in embodied fish than for catch
(embodied_fish_rank <- 
  fread("/mnt/rdsi/github/feed_pressure_mapping/data/tidy_data/demand/embodied_fish_per_cell.csv") |> 
  lazy_dt() |> 
  group_by(diet, source_code, TaxonName, CommonName) |> 
  summarise(total_demand_ge = sum(total_embodied_fish_ge, na.rm = TRUE),
            total_demand_mass = sum(total_embodied_fish_mass, na.rm = TRUE)) |> 
  filter(diet == "marine_diet") |> 
  arrange(-total_demand_mass) |> 
  as_tibble())


(fish_catch_rank <- 
  fread("/mnt/rdsi/github/feed_pressure_mapping/data/tidy_data/demand/embodied_fish_per_cell.csv") |> 
  lazy_dt() |> 
  group_by(diet, source_code, TaxonName, CommonName) |> 
  summarise(total_catch = sum(total_catch, na.rm = TRUE)) |> 
  filter(diet == "marine_diet") |> 
  arrange(-total_catch) |> 
  as_tibble())
```

#clear the environment

```{r}
rm(list = ls(all.names = TRUE))

```


