---
title: "20_ingredient_case_studies"
author: "Rich Cottrell"
date: "14/02/2023"
output: html_document
---


Set up
```{r}
library(tidyverse)
library(ggpubr)
library(patchwork)
library(here)
library(sf)
library(terra)
library(rnaturalearth)
#library(rnaturalearthdata)
library(RColorBrewer)
library(gameofthrones)
library(parallel)
library(ggdist)
library(data.table)
library(dtplyr)


# taking cumulative impoact palette from Halpern et al 
red <- "#B90000"
d_brown <- "#515256"
m_brown <- "#B27B54"
l_brown <- "#BC995F"
green <- "#A8B072"
yellow<- "#EFCE71"
l_yellow <- "#F7F6C1"
light_gray <- "#F8F9FA"
discrete_pal <- c(l_yellow, yellow, green, l_brown, m_brown, d_brown, "firebrick")
continuous_pal <-  colorRampPalette(discrete_pal, space="Lab", bias = 3.5)(10000)
final_palette <- c(light_gray, continuous_pal, red)

#source files
source(here("src/fxns.R"))

#spatial products
moll_crs <- "ESRI:53009"
gp_crs <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"


countries <-    ne_countries(scale = "medium", returnclass = "sf") |> st_transform(crs = moll_crs)
bbox <- ne_download(scale = 50, type = "wgs84_bounding_box", category = "physical", returnclass = "sf") |> st_transform(crs = moll_crs)
coastline <- ne_coastline(scale = 50, returnclass = "sf") |> st_transform(crs = moll_crs)
select <- dplyr::select
values <- terra::values
```

Now some case studies of ingredients 


Fish oil - disturbance

```{r}
list.files(here("data/spatial/marine_diet/int"), pattern = "fish oil_disturbance_km2_gp", full=TRUE) |> rast() |> global(fun = sum, na.rm=TRUE)
list.files(here("data/spatial/plant_diet/int"), pattern = "fish oil_disturbance_km2_gp", full=TRUE) |> rast() |> global(fun = sum, na.rm=TRUE)
marine_diet_disturbance <- 
  bind_rows(
  
  fo_low_epc_r <- list.files(here("data/spatial/marine_diet/int"), pattern = "fish oil_disturbance_km2_gp", full=TRUE) |> pluck(1) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "Eastern Pacific"),
  
  fo_hi_nat_r <- list.files(here("data/spatial/marine_diet/int"), pattern = "fish oil_disturbance_km2_gp", full=TRUE) |> pluck(2) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "North Atlantic")
) |> mutate(pressure = "Disturbance km2",
            diet = "Marine-dominant feed") |> 
  rename(value = lyr.1)
plant_diet_disturbance <- 
  bind_rows(
  
  fo_low_epc_r <- list.files(here("data/spatial/plant_diet/int"), pattern = "fish oil_disturbance_km2_gp", full=TRUE) |> pluck(1) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "Eastern Pacific"),
  
  fo_hi_nat_r <- list.files(here("data/spatial/plant_diet/int"), pattern = "fish oil_disturbance_km2_gp", full=TRUE) |> pluck(2) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "North Atlantic")
) |> mutate(pressure = "Disturbance km2",
            diet = "Plant-dominant feed") |> 
  rename(value = lyr.1)
fish_oil_disturbance_epc_nat <- bind_rows(marine_diet_disturbance, plant_diet_disturbance)
get_bounds <- fish_oil_disturbance_epc_nat |> select(x,y, value) |> rast(type="xyz")
crs(get_bounds) <- gp_crs
fish_oil_bounds <- st_bbox(get_bounds)
fo_bounds_df <- tibble(xmin = fish_oil_bounds["xmin"] , xmax = fish_oil_bounds["xmax"] , ymin = fish_oil_bounds["ymin"] , ymax = fish_oil_bounds["ymax"])
fo_dist_p <- ggplot()+
  geom_rect(data = fo_bounds_df, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), fill = "aliceblue", alpha = 0.7)+
  geom_tile(data = fish_oil_disturbance_epc_nat, aes(x = x, y = y, fill = value))+
  geom_sf(data = ne_countries(scale = 10, returnclass = "sf") |> st_transform(crs = gp_crs) |> st_crop(y = fish_oil_bounds), size = NA, fill="grey75")+
  facet_grid(rows = vars(source), cols = vars(diet))+
  scale_fill_gradientn(colours = rcartocolor::carto_pal(n = 7, name = "SunsetDark"))+
  theme_bw()+
  theme(axis.text = element_blank(),
        axis.title.y = element_text(vjust = 3, size = 12),
        axis.title.x = element_blank(),
        axis.ticks = element_blank(),
        legend.box.spacing = unit(-0.8, "cm"),
        legend.title = element_text(size = 8))+
  labs(fill = expression(paste("Disturbance (km"^{2}*")")), y = "Fish oil - Disturbance")
  
ggsave(filename = here("explore/fish_oil_comparisons.jpg"), device = "jpg", dpi = 600, width = 18, height = 12, units = "cm")
```


Wheat - GHG

```{r}
list.files(here("data/spatial/marine_diet/int"), pattern = "wheat_N_gp", full=TRUE) |> rast() |> global(fun = sum, na.rm=TRUE)
list.files(here("data/spatial/plant_diet/int"), pattern = "wheat_N_gp", full=TRUE) |> rast() |> global(fun = sum, na.rm=TRUE)
marine_diet_wheat_N <- 
  bind_rows(
  
  wheat_low_ukr_r <- list.files(here("data/spatial/marine_diet/int"), pattern = "wheat_N_gp", full=TRUE) |> pluck(3) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "Ukraine"),
  
  wheat_low_ukr_r <- list.files(here("data/spatial/marine_diet/int"), pattern = "wheat_N_gp", full=TRUE) |> pluck(2) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "Pakistan")
  ) |>  
  mutate(pressure = "kg N eq.",
            diet = "Marine-dominant feed") |> 
  rename(value = N_eq)
plant_diet_wheat_N <- 
  bind_rows(
  
  wheat_low_ukr_r <- list.files(here("data/spatial/plant_diet/int"), pattern = "wheat_N_gp", full=TRUE) |> pluck(3) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "Ukraine"),
  
  wheat_low_ukr_r <- list.files(here("data/spatial/plant_diet/int"), pattern = "wheat_N_gp", full=TRUE) |> pluck(2) |> rast() |> terra::as.data.frame(xy = TRUE) |> mutate(source = "Pakistan")
  ) |>  
  mutate(pressure = "kg N eq.",
            diet = "Plant-dominant feed") |> 
  rename(value = N_eq)
wheat_N_ukr_pak <- bind_rows(marine_diet_wheat_N, plant_diet_wheat_N)
get_bounds_2 <- wheat_N_ukr_pak |> select(x,y, value) |> rast(type="xyz")
crs(get_bounds_2) <- gp_crs
wheat_bounds <- st_bbox(get_bounds_2)
wheat_bounds_df <- tibble(xmin = wheat_bounds["xmin"] , xmax = wheat_bounds["xmax"] , ymin = wheat_bounds["ymin"] , ymax = wheat_bounds["ymax"])
wheat_N_p <- 
  ggplot()+
  geom_rect(data = wheat_bounds_df, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), fill = "aliceblue", alpha = 0.7)+
  geom_sf(data = ne_countries(scale = 10, returnclass = "sf") |> st_transform(crs = gp_crs) |> st_crop(y = wheat_bounds), size = 0.3, colour="grey50", fill="grey75")+
  geom_tile(data = wheat_N_ukr_pak, aes(x = x, y = y, fill = value))+
  
  facet_grid(rows = vars(source), cols = vars(diet))+
  scale_fill_gradientn(colours = rcartocolor::carto_pal(n = 7, name = "TealGrn"))+
  theme_bw()+
  theme(axis.text = element_blank(),
        axis.title.y = element_text(vjust = 3, size = 12),
        axis.title.x = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 8),
        plot.margin = unit(c(t = 0, b = 0, l=0.3, r=0.3), "cm"))+
  labs(fill = "kg N eq.", y = "Wheat - Nitrogen pollution")
  
ggsave(filename = here("explore/wheat_comparisons.jpg"), device = "jpg", dpi = 600, width = 18, height = 12, units = "cm")
```

Combine plots

```{r}
(fo_dist_p/wheat_N_p)+
  plot_annotation(tag_levels = "a")+
  plot_layout(heights = c(1.2,1))
ggsave(filename = here("figures/ingredient_casestudies.jpg"), device = "jpg", dpi = 600, width = 18, height = 26, units = "cm")
```