---
title: "Tidying data"
author: "Rich Cottrell"
date: "15/02/2022"
output: html_document
---

```{r}
library(tidyverse)
library(parallel)
library(raster)
library(janitor)
library(here)
library(countrycode)
library(rredlist)

source(here("src/directories.R"))
```


This is the code to unzip and adjust the extents of the mapspam rasters (-180, 180, -90, 90) - DO NOT RUN IN PROJECT - here as a backup to scripts in the raw data files

```{r}


mapspam_zip_files <- list.files(path = mapspam_dir, pattern = "\\.zip$")


lapply(X=mapspam_zip_files, FUN = unzip)


#Adjust the extent of rasters to full lon lat coveragge

#test
banana <- raster(file.path(mapspam_dir, "spam2010V2r0_global_H_BANA_H.tif"))
banana

#this should be the new extent for all
new_extent <- c(-180, 180, -90, 90)

extent(banana) <- new_extent

#apply new extents to all files

tifs <- list.files(dir, pattern = "\\.tif")

adjust_extent <- function(this_file){
  message(paste("processing", which(tifs==this_file), "of", length(tifs)))
  this_raster <- raster(this_file)
  extent(this_raster) <- new_extent
  writeRaster(x=this_raster, filename = file.path("/mnt/rdsi/raw_data/MAPSPAM/new-extents", this_file), overwrite = TRUE)
}

#run over mutliple cores to speed things up
parallel::mclapply(X = tifs, FUN = adjust_extent, mc.cores = 6)


```

This is the code to unzip the gridded livestock of the world rasters - DO NOT RUN IN PROJECT - here as a backup to scripts in the raw data files

```{r}

dir <- "/mnt/rdsi/raw_data/gridded-livestock-of-the-world"

setwd(dir)

library(tidyverse)
library(parallel)
library(raster)

glw_zip_files <- list.files(dir, pattern = "\\.zip$")

unzip_raw_data <- function(this_file){
  this_file_name <- file.path(dir, this_file)
  unzip(this_file_name)
  
}


lapply(X = glw_zip_files, FUN = unzip_raw_data)



```


Tidy global aquaculture production data

```{r}

(aqua_prod_raw <- read.csv(file.path(fishstat_dir, "aqua-prod-raw.csv")) %>% 
  clean_names() %>% 
  rename(country= country_country,
         species = species_asfis_species,
         area = aquaculture_area_fao_major_fishing_area,
         environment = environment_environment)
)


#sorts country coding to deal with non-UTF characters that country code depends on
Encoding(aqua_prod_raw$country) <- "latin1" #deals with the non-UTF
aqua_prod_raw$country <- iconv(aqua_prod_raw$country, "latin1", "UTF-8",sub='')



aquaculture_prod <- aqua_prod_raw %>% 
  pivot_longer(names_to = "year", values_to = "value", -c(country, species, area, environment, unit)) %>% 
  mutate(iso_3c = countrycode(country, origin = "country.name", destination = "iso3c", warn = TRUE)) %>%
  mutate(iso_3c = case_when(country == "Zanzibar" ~ "TZA",
                            TRUE ~ iso_3c)) %>% 
    mutate(year = gsub("x", "", year) %>% 
              as.numeric,
           flag = case_when(value == "..." ~ "No data",
                           value == " " ~ "Data not separately available",
                           value == "-" ~ "Nil or zero",
                           value == "0 0" ~ "0<x<0.5",
                           grepl(" F", value) ~ "estimate",
                           TRUE ~ "Reported"),
           value = case_when(value %in% c("...", " ", "-") ~ "0",
                           value == "0 0" ~ "0.25",
                           grepl(" F", value) ~ gsub(" F", "", value),
                           TRUE ~ value) %>% 
              as.numeric) %>% 
   filter(country != "Totals")

  
saveRDS(object = aquaculture_prod, file = here("data", "tidy_data", "aquaculture_production_tidy.rds"))


```

